# -*- coding: utf-8 -*-
"""Dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gibema3ispYX_GvJgmMU7M1z5YTtEEiw
"""

!pip install streamlit pandas matplotlib

import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = {
    "Queries": ["How many numbers of app installed?", "Explain Operating system", "What is Device Model?"],
    "Topics": ["AI", "AI", "NLP"],
    "Satisfaction_Rating": [4, 5, 5]
}

df = pd.DataFrame(data)

# Dashboard layout
st.title('Chatbot Analytics Dashboard')

# Display the most common topics and user satisfaction
st.subheader("Most Common Topics")
st.bar_chart(df['Topics'].value_counts())
st.subheader("User Satisfaction Ratings")
st.line_chart(df['Satisfaction_Rating'])

streamlit run dashboard.py